const TechnicalData = [
  {
    id: 1,
    name: "Prof. Guo-En Chang",
    description: "National Chung Cheng University, Taiwan",
    email: "imegec@ccu.edu.tw",
  },
  {
    id: 2,
    name: "Prof. Judy Rorison",
    description: "University of Bristol, United Kingdom",
    email: "Judy.Rorison@bristol.ac.uk",
  },
  {
    id: 23,
    name: "Prof. Sudeb Dasgupta",
    description: "Indian Institute of Technology Roorkee, India",
    email: "sudeb.dasgupta@ece.iitr.ac.in",
  },
  {
    id: 28,
    name: "Prof. Neeta Pandey",
    email: "neetapandey@dce.ac.in",
    description: "Delhi Technological University, India",
  },
  {
    id: 3,
    name: "Dr. S. H. Laskar",
    description: "National Institute of Technology Silchar, India",
    email: "rhlaskar@ece.nits.ac.in",
  },
  {
    id: 4,
    name: "Prof. Rashmi Gupta",
    description: "Netaji Subhas University of Technology, Delhi, India",
    email: "rashmig71@yahoo.com",
  },
  {
    id: 5,
    name: "Prof. Munho Kim",
    description: "Nanyang Technological University, Singapore",
    email: "munho.kim@ntu.edu.sg",
  },
  {
    id: 6,
    name: "Dr. Anirban Bandyopadhyay",
    description: "GLOBALFOUNDRIES, Inc., Santa Clara, California, USA",
    email: "Anirban_bandy0@ieee.org",
  },
  {
    id: 7,
    name: "Dr. Amitesh Kumar",
    description: "Indian Institute of Technology (ISM) Dhanbad, India",
    email: "amitesh@iitism.ac.in",
  },
  {
    id: 8,
    name: "Prof. John Dallesasse",
    description: "University of Illinois, Urbana-Champaign, USA",
    email: "jdallesa@illinois.edu",
  },
  {
    id: 9,
    name: "Prof. Richa Bhatia",
    description: "Netaji Subhas University of Technology, Delhi, India",
    email: "richatimes@gmail.com",
  },
  {
    id: 10,
    name: "Prof. Manju Khari",
    description: "Jawaharlal Nehru University, Delhi, India",
    email: "manjukhari@mail.jnu.ac.in",
  },
  {
    id: 11,
    name: "Prof. Bijay K Das",
    description: "Indian Institute of Technology Madras",
    email: "bkdas@ee.iitm.ac.in",
  },
  {
    id: 12,
    name: "Dr. Garima Srivastava",
    description: "Netaji Subhas University of Technology East Campus, Delhi",
    email: "garima.shrivastav@gmail.com",
  },
  {
    id: 13,
    name: "Dr. Rohit Kumar",
    description: "Delhi Technological University, Delhi",
    email: "rohit.kumar@dce.ac.in",
  },
  {
    id: 14,
    name: "Dr. Arun Kumar",
    description: "National Institute of Technology Silchar",
    email: "arunkumar@ece.nits.ac.in",
  },
  {
    id: 15,
    name: "Prof. Geeta Sikka",
    description: "National Institute of Technology Delhi",
    email: "hodcs@nitdelhi.ac.in",
  },
  {
    id: 16,
    name: "Prof. Samit K Ray",
    description: "Indian Institute of Technology Kharagpur",
    email: "physkr@phy.iitkgp.ac.in",
  },
  {
    id: 17,
    name: "Dr. Deepti Kakkar",
    description: "Dr B R Ambedkar National Institute of Technology, Jalandhar",
    email: "kakkard@nitd.ac.in",
  },
  {
    id: 18,
    name: "Dr. Arti Jain",
    description: "Netaji Subhas University of Technology East Campus, Delhi",
    email: "rtjain2001@gmail.com",
  },
  {
    id: 19,
    name: "Dr. Govind Murmu",
    description: "Indian Institute of Technology (ISM) Dhanbad",
    email: "govind@iitism.ac.in",
  },
  {
    id: 20,
    name: "Dr. Tripti Goel",
    description: "National Institute of Technology Silchar",
    email: "triptigoel@ece.nits.ac.in",
  },
  {
    id: 21,
    name: "Prof. Poornima Mittal",
    description: "Delhi Technological University, Delhi",
    email: "poornimamittal@dce.ac.in",
  },
  {
    id: 22,
    name: "Prof. Mukesh Kumar",
    description: "Indian Institute of Technology Indore",
    email: "Mukesh.kr@iiti.ac.in",
  },
  {
    id: 24,
    name: "Prof. Tarun Kanti Bhattacharyya",
    description: "Indian Institute of Technology Kharagpur",
    email: "tkb@ece.iitkgp.ac.in",
  },
  {
    id: 25,
    name: "Dr. Amita Jain",
    description: "Netaji Subhas University of Technology East Campus, Delhi",
    email: "amita_jain_17@yahoo.com",
  },
  {
    id: 26,
    name: "Dr. S. K. Tripathy",
    description: "National Institute of Technology Silchar",
    email: "sktripathy@ece.nits.ac.in",
  },
  {
    id: 27,
    name: "Dr. Balwinder Raj",
    description: "Dr B R Ambedkar National Institute of Technology, Jalandhar",
    email: "rajb@nitj.ac.in",
  },
  {
    id: 29,
    name: "Mr. Preet Yadav",
    description:
      "NXP Semiconductors, Noida, India",
    email: "preet.yadav@nxp.com",
  },
  {
    id: 30,
    name: "Dr. Neetu Sood",
    description: "Dr B R Ambedkar National Institute of Technology, Jalandhar",
    email: "soodn@nitj.ac.in",
  },
  {
    id: 31,
    name: "Dr. Devendra Chack",
    description: "Indian Institute of Technology (ISM) Dhanbad",
    email: "devendra@iitism.ac.in",
  },
  {
    id: 32,
    name: "Dr. Anuradha Chug",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "anuradha@ipu.ac.in",
  },
  {
    id: 33,
    name: "Dr. Ashish Payal",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "ashish@ipu.ac.in",
  },
  {
    id: 34,
    name: "Dr. Rahul Johari",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "rahul@ipu.ac.in",
  },
  {
    id: 35,
    name: "Prof. Brahamjeet Singh",
    description: "National Institute of Technology Kurukshetra",
    email: "brahmjit@nitkkr.ac.in",
  },
  {
    id: 36,
    name: "Prof. H. M. Gupta",
    description: "Indian Institute of Technology Delhi",
    email: "hmgupta@ee.iitd.ac.in",
  },
  {
    id: 37,
    name: "Prof. Shaibal Mukherjee",
    description: "Indian Institute of Technology Indore",
    email: "shaibal@iiti.ac.in",
  },
  {
    id: 38,
    name: "Prof. M. P. S. Bhatia",
    description: "Netaji Subhas University of Technology, Delhi",
    email: "mpsbhatia@nsut.ac.in",
  },
  {
    id: 39,
    name: "Prof. Manoj Gaur",
    description: "Netaji Subhas University of Technology, Delhi",
    email: "manojgaur@yahoo.com",
  },
  {
    id: 40,
    name: "Prof. O. P. Sahu",
    description: "National Institute of Technology Kurukshetra",
    email: "ops_nitk@yahoo.co.in",
  },
  {
    id: 41,
    name: "Prof. Subhananda Chakraborty",
    description: "Indian Institute of Technology Bombay",
    email: "subho@ee.iitb.ac.in",
  },
  {
    id: 42,
    name: "Prof. Sandeep Arya",
    description:
      "Guru Jambheshwar University of Science and Technology, Hisar, Haryana",
    email: "arya1sandeep@gmail.com",
  },
  {
    id: 43,
    name: "Prof. Sandeep Kumar",
    description: "Punjab Engineering College, Chandigarh",
    email: "sandeepk@gmail.com",
  },
  {
    id: 44,
    name: "Dr. Ramesh Kumar Vats",
    description:
      "National Institute of Technology Hamirpur, Himachal Pradesh, India",
    email: "rkvats@nith.ac.in",
  },
  {
    id: 45,
    name: "Prof. Amit Garg",
    description:
      "Deenbandhu Chhotu Ram University of Science and Technology, Murthal, Haryana",
    email: "garg_amit03@yahoo.co.in",
  },
  {
    id: 46,
    name: "Prof. Yogesh Chaba",
    description:
      "Guru Jambheshwar University of Science and Technology, Hisar, Haryana",
    email: "yogeshchaba@yahoo.com",
  },
  {
    id: 47,
    name: "Prof. Dinesh Kumar",
    description: "Delhi Technological University, Delhi",
    email: "dinesh_chutani@yahoo.com",
  },
  {
    id: 48,
    name: "Prof. Amit Prakash Singh",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "amit@ipu.ac.in",
  },
  {
    id: 49,
    name: "Prof. Anjana Gosain",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "anjana_gosain@ipu.ac.in",
  },
  {
    id: 50,
    name: "Prof. Bharti Suri",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "bhartisuri@gmail.com",
  },
  {
    id: 51,
    name: "Prof. Virendra Prasad Vishwakarma",
    description: "Guru Gobind Singh Indraprastha University, New Delhi",
    email: "vpv@ipu.ac.in",
  },
  {
    id: 52,
    name: "Prof. Ajay Singholi",
    description:
      "Guru Gobind Singh Indraprastha University, East Campus, New Delhi",
    email: "ajay.s@ipu.ac.in",
  },
];

export default TechnicalData;
